# Use `conda env create environment.yml` to create a dev environment
name: ml_env
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-learn-intelex
  - pip
  - jupyter
